version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - echo Nothing to do in the install phase...
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - echo Build started on `date`
       - ./gradlew build
  post_build:
    commands:
       - echo Build completed on `date`
      # - command
artifacts:
  files:
     - build/lib/gs-spring-boot-0.1.0.jar
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths